name: build

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Cache 
        uses: actions/cache@v3.2.3
        with:
          path: ~/.npm
          key: buildCache
      - run: npm ci
      - run: npm test --  --coverage
        env:
          CI: true
      - name: upload code coverage
        uses: actions/upload-artifact@v3.1.2
        with:
          name: codecoverage
          path: coverage
      - name: build
        run: npm run build
      - name: upload build files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: https://crooked-girl.surge.sh
    steps:
      - name: download build
        uses: actions/download-artifact@v3.0.2
        with:
          name: build
      - name: deploy to surge
        run: npx surge --project '.' --domain crooked-girl.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
